version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "4.7.x"
    schedule:
      interval: daily
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "5.0.x"
    schedule:
      interval: daily
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "4.6.x"
    schedule:
      interval: daily

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"